<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OntoTwin-ZHHZ-Launcher</AssemblyName>
    <RootNamespace>OntoTwin.ZHHZ.Launcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <Version>3.7.1.1002</Version>
    <ApplicationIcon>LingYunZhi.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="logo-flat.png" />
    <Resource Include="LingYunZhi.ico" />
  </ItemGroup>
</Project>
